# 5 Numpy Functions you should know


###  Numpy

Numpy is a module for Python,which stands for "Numerical Python".It is a python package for scientific computing that provides high-performance multi-dimensional array objects. 

- numpy.argmax()
- numpy.isnan()
- numpy.vstack()
- numpy.insert()
- numpy.repeat()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [1]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.argmax
function2 = np.isnan
function3 = np.vstack
function4 = np.hstack
function5 = np.repeat

## Function 1 - np.argmax()

This function returns the indices of the maximum values along an axis

In [6]:
# Example 1 - working 
arr1 = np.array([[1,2,3],[4,5,6]])
print("index of max value is:",np.argmax(arr1))

index of max value is: 5


We can obtain the index of the maximum value in the array

In [10]:
# Example 2 - working
arr2 = np.array([[7,8,9],
                 [4,5,6],
                 [10,3,5]])
print("index of max value along 0 axis is:",np.argmax(arr2,axis=0))
print("index of max value along 1 axis is:",np.argmax(arr2,axis=1))

index of max value along 0 axis is: [2 0 0]
index of max value along 1 axis is: [2 2 0]


We can obtain the index of the maximum value in the array on x and y axis

In [11]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([1,2,3])
np.argmax(arr3,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

Here we are check the for max value index in array along y axis which is not there.

This function can be very useful when we wanted to know the index of max value in matrix with n dimensions and also in reinforcement learning tasks.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 2 - np.isnan()

This function is used to know  if there is NAN in dataset.

In [12]:
# Example 1 - working
arr1 = np.array([[1,9,8],[3,2,1],[6,7,4]])
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

Here we can see all false because there is no nan value 

In [18]:
# Example 2 - working
arr2 = np.array([[1,9,7],[0,2,1],[7,1,4.]])
arr2[0,1] = np.nan
arr2[2,2] = np.nan
np.isnan(arr2)

array([[False,  True, False],
       [False, False, False],
       [False, False,  True]])

After adding the nan now we can see the true as there are nan values

In [19]:
# Example 3 - breaking (to illustrate when it breaks)
np.isnan(np.array([[np.nan, 8],
                   [6, 11]], 
                  dtype=object))

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

A NAN Values can't be inserted in the type of object

Used to find the NaN values in the dataset

In [32]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 3 - np.vstack()

Concatenates the arrays along columns(Vertically)

In [20]:
# Example 1 - working
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Concatenates the arr1 and arr2. 

In [21]:
# Example 2 - working
lis1 = [1,2,3,4]
lis2 = [6,7,8,9]
np.vstack((lis1,lis2))

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

Concatenates the two lists lis1 and lis2 vertically into a single array

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6,2],[7,8,9]])
np.vstack((arr1,arr2))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

The no of values in the both the arrays are different to concatenate it should match

Used to Concatenate the data vertically

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 4 - np.insert()

this will be used to insert values.

In [24]:
# Example 1 - working
arr1 = np.array([[1,2,3],[4,5,6]])
np.insert(arr1,2,[10,12])

array([ 1,  2, 10, 12,  3,  4,  5,  6])

List of 10,12 is inserted at pos 2 

In [26]:
# Example 2 - working
arr2 = np.array([[1,2,3],[4,5,6]])
np.insert(arr2,2,[10,12,14],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 12, 14]])

List of 10,12,14 is inserted at row 2 as we gave the axis=0

In [27]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.array([[1,2,3],[4,5,6]])
np.insert(arr2,2,[10,12],axis=0)

ValueError: could not broadcast input array from shape (1,2) into shape (1,3)

Values can't be inserted as the shape is not same to insert or avoid this error we need to give the same shape(1,3)

Very helpful in inserting values

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'

## Function 5 - np.repeat()

function repeats the elements of an array

In [28]:
# Example 1 - working
np.repeat(3,5)

array([3, 3, 3, 3, 3])

it will repeat the value 3 five times

In [31]:
# Example 2 - working
np.repeat(a=[8,9],repeats=3)

array([8, 8, 8, 9, 9, 9])

to repeat the multiple values n times (here we are repeating 8,9 values 3 times)

In [37]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1,4],[7,6]])
rep1 = np.repeat(a=arr1,repeats=2,axis=0)
print("Repeating values Downward using axis 0;",rep1)
rep2 = np.repeat(a=3,repeats=5,axis=1)
print(rep2)

Repeating values Downward using axis 0; [[1 4]
 [1 4]
 [7 6]
 [7 6]]


AxisError: axis 1 is out of bounds for array of dimension 1

As in the rep2 we gave the axis as 1 we get the error as out of bounds

Very helpful in repeating values and also duplicating the matrix or duplicate rows.

In [38]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Updating notebook "ganeshtharun98/numpy-array-operations" on https://jovian.com
[jovian] Committed successfully! https://jovian.com/ganeshtharun98/numpy-array-operations


'https://jovian.com/ganeshtharun98/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>